<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FilmSeeder extends Seeder
{
    public function run()
    {
        $films = [
            [
                'judul' => 'Interstellar',
                'tahun' => 2014,
                'sinopsis' => 'Sekelompok penjelajah menggunakan wormhole untuk melampaui batasan perjalanan ruang angkasa.',
                'rating_avg' => 4.8,
                'rating_default' => 0, // Ditambahkan sesuai foto
                'is_active' => true,   // Ditambahkan sesuai foto
                'poster' => 'posters/interstellar.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'The Dark Knight',
                'tahun' => 2008,
                'sinopsis' => 'Batman harus menerima ujian psikologis dan fisik terbesarnya untuk melawan Joker.',
                'rating_avg' => 4.9,
                'rating_default' => 0,
                'is_active' => true,
                'poster' => 'posters/dark-knight.jpg', 
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Spirited Away',
                'tahun' => 2001,
                'sinopsis' => 'Seorang gadis berusia 10 tahun mengembara ke dunia yang dikuasai oleh roh dan dewa.',
                'rating_avg' => 4.7,
                'rating_default' => 0,
                'is_active' => true,
                'poster' => 'posters/spirited-away.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Parasite',
                'tahun' => 2019,
                'sinopsis' => 'Keserakahan mengancam hubungan simbiosis antara keluarga kaya dan miskin.',
                'rating_avg' => 4.6,
                'rating_default' => 0,
                'is_active' => true,
                'poster' => 'posters/parasite.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Inception',
                'tahun' => 2010,
                'sinopsis' => 'Pencuri yang memasuki mimpi orang lain diberi tugas untuk menanamkan ide ke dalam pikiran seorang CEO.',
                'rating_avg' => 4.8,
                'rating_default' => 0,
                'is_active' => true,
                'poster' => 'posters/inception.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Oppenheimer',
                'tahun' => 2023,
                'sinopsis' => 'Kisah J. Robert Oppenheimer dan perannya dalam pengembangan bom atom.',
                'rating_avg' => 4.7,
                'rating_default' => 0,
                'is_active' => true,
                'poster' => 'posters/oppenheimer.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Dune Part Two',
                'tahun' => 2024,
                'sinopsis' => 'Paul Atreides bersatu dengan Chani dan Fremen untuk membalas dendam.',
                'rating_avg' => 4.5,
                'rating_default' => 0,
                'is_active' => true,
                'poster' => 'posters/dune.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Past Lives',
                'tahun' => 2023,
                'sinopsis' => 'Dua teman masa kecil bertemu kembali di New York setelah berpisah selama dua dekade.',
                'rating_avg' => 4.4,
                'rating_default' => 0,
                'is_active' => true,
                'poster' => 'posters/past-lives.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kuasa Gelap',
                'tahun' => 2024,
                'sinopsis' => 'Kisah perjuangan seorang romo muda yang sedang goyah imannya dan seorang romo eksorsis senior dalam menyelidiki serta melakukan ritual pengusiran setan Katolik demi menyelamatkan seorang remaja perempuan.',
                'rating_avg' => 3.8,
                'rating_default' => 0,
                'is_active' => true,
                'poster' => 'posters/kuasa-gelap.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'KKN di Desa Penari',
                'tahun' => 2022,
                'sinopsis' => 'Enam mahasiswa yang menjalani program KKN di desa terpencil harus menghadapi teror mistis mengerikan dari sosok penari gaib akibat melanggar aturan adat setempat.',
                'rating_avg' => 3.0,
                'rating_default' => 0,
                'is_active' => true,
                'poster' => 'posters/kkn-di-desa-penari.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Susuk',
                'tahun' => 2023,
                'sinopsis' => 'Seorang perempuan mencoba melepas susuk di tubuhnya agar bisa bertobat, namun susuk tersebut telanjur membusuk dan membawa kutukan berupa teror gaib mengerikan bagi orang-orang di sekitarnya.',
                'rating_avg' => 2.6,
                'rating_default' => 0,
                'is_active' => true,
                'poster' => 'posters/susuk.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kang Mak from Pee Mak',
                'tahun' => 2024,
                'sinopsis' => 'Seorang tentara yang baru pulang dari medan perang tidak menyadari bahwa istri tercintanya yang sedang menggendong anak mereka sebenarnya sudah meninggal dan kini menjadi hantu.',
                'rating_avg' => 3.5,
                'rating_default' => 0,
                'is_active' => true,
                'poster' => 'posters/kang-mak-from-pee-mak.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kaka Boss',
                'tahun' => 2024,
                'sinopsis' => 'Seorang penagih utang (debt collector) asal Indonesia Timur yang disegani di Jakarta memutuskan beralih profesi menjadi penyanyi demi membuat anak perempuan satu-satunya merasa bangga.',
                'rating_avg' => 2.3,
                'rating_default' => 0,
                'is_active' => true,
                'poster' => 'posters/kaka-boss.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Agak Laen',
                'tahun' => 2024,
                'sinopsis' => 'Empat sekawan pengelola rumah hantu pasar malam yang hampir bangkrut secara tidak sengaja menyebabkan seorang pengunjung meninggal serangan jantung, lalu menguburnya di dalam wahana hingga rumah hantu mereka justru menjadi viral.',
                'rating_avg' => 3.8,
                'rating_default' => 0,
                'is_active' => true,
                'poster' => 'posters/agak-laen.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Hangout',
                'tahun' => 2016,
                'sinopsis' => 'Sembilan publik figur diundang ke sebuah pulau terpencil, namun satu per satu dari mereka mulai dibunuh secara misterius oleh sosok tak dikenal.',
                'rating_avg' => 3.1,
                'rating_default' => 0,
                'is_active' => true,
                'poster' => 'posters/hangout.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Warkop DKI Reborn',
                'tahun' => 2016,
                'sinopsis' => 'Aksi kocak tiga anggota lembaga keamanan CHIPS (Dono, Kasino, Indro) dalam menangkap penjahat yang justru selalu berakhir dengan kekacauan dan denda besar yang harus mereka bayar.',
                'rating_avg' => 3.0,
                'rating_default' => 0,
                'is_active' => true,
                'poster' => 'posters/warkop-dki.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Onde Mande!',
                'tahun' => 2023,
                'sinopsis' => 'Siasat cerdik warga sebuah desa di pesisir Danau Maninjau untuk memanipulasi kematian seorang tetua desa demi mengklaim hadiah undian 2 miliar rupiah untuk pembangunan desa mereka.',
                'rating_avg' => 3.4,
                'rating_default' => 0,
                'is_active' => true,
                'poster' => 'posters/onde-mande.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Pertaruhan',
                'tahun' => 2017,
                'sinopsis' => 'Perjuangan nekat empat saudara laki-laki yang melakukan aksi kriminal demi mengumpulkan uang dalam waktu singkat untuk biaya pengobatan ayah mereka yang sakit keras.',
                'rating_avg' => 3.4,
                'rating_default' => 0,
                'is_active' => true,
                'poster' => 'posters/pertaruhan.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Gundala',
                'tahun' => 2019,
                'sinopsis' => 'Kisah asal-usul Sancaka, seorang anak jalanan yang tumbuh di lingkungan keras dan mendapatkan kekuatan petir, yang kemudian bangkit sebagai pahlawan super untuk melawan ketidakadilan di kotanya.',
                'rating_avg' => 3.1,
                'rating_default' => 0,
                'is_active' => true,
                'poster' => 'posters/gundala.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Hit & Run',
                'tahun' => 2019,
                'sinopsis' => 'Aksi seorang polisi selebriti yang narsis dalam memburu gembong narkoba kelas kakap, di mana ia terpaksa bekerja sama dengan seorang penyanyi pop, penipu receh, dan remaja culun.',
                'rating_avg' => 3.5,
                'rating_default' => 0,
                'is_active' => true,
                'poster' => 'posters/hit-and-run.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Ali Topan',
                'tahun' => 2024,
                'sinopsis' => 'Kisah petualangan dan romansa jalanan antara Ali Topan, seorang pemuda pemberontak yang vokal terhadap ketidakadilan, dengan seorang gadis kaya yang dikekang oleh keluarganya.',
                'rating_avg' => 2.9,
                'rating_default' => 0,
                'is_active' => true,
                'poster' => 'posters/ali-topan.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Dear Nathan: Thank You Salma',
                'tahun' => 2022,
                'sinopsis' => 'Kelentuan kisah cinta Nathan dan Salma yang mulai diuji oleh perbedaan idealisme di dunia aktivisme kampus, serta munculnya orang ketiga di antara mereka.',
                'rating_avg' => 3.6,
                'rating_default' => 0,
                'is_active' => true,
                'poster' => 'posters/dear-nathan.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Milea: Suara dari Dilan',
                'tahun' => 2020,
                'sinopsis' => 'Sudut pandang Dilan dalam menceritakan kembali kenangan manis, konflik geng motor, hingga alasan di balik kandasnya hubungan cintanya yang legendaris bersama Milea.',
                'rating_avg' => 3.1,
                'rating_default' => 0,
                'is_active' => true,
                'poster' => 'posters/milea.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Dilan 1990',
                'tahun' => 2018,
                'sinopsis' => 'Awal mula kisah cinta ikonik di Bandung antara Milea, siswi pindahan dari Jakarta, dengan Dilan, seorang panglima geng motor yang menaklukkannya lewat cara-cara pendekatan yang unik dan puitis.',
                'rating_avg' => 3.6,
                'rating_default' => 0,
                'is_active' => true,
                'poster' => 'posters/dilan.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Galaksi',
                'tahun' => 2023,
                'sinopsis' => 'Kisah cinta penuh konflik antara Galaksi, seorang ketua geng motor sekolah yang tangguh, dengan Kejora, seorang gadis anggota paskibraka yang polos.',
                'rating_avg' => 3.2,
                'rating_default' => 0,
                'is_active' => true,
                'poster' => 'posters/galaksi.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Galih & Ratna',
                'tahun' => 2017,
                'sinopsis' => 'Pertemuan dan kisah cinta dua remaja SMA yang sama-sama sedang mencari jati diri serta mengejar mimpi mereka lewat kecintaan terhadap musik dan kaset lama.',
                'rating_avg' => 3.2,
                'rating_default' => 0,
                'is_active' => true,
                'poster' => 'posters/galih-ratna.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Sekawan Limo',
                'tahun' => 2024,
                'sinopsis' => 'Kisah lima pendaki yang tersesat di sebuah gunung mistis karena melanggar mitos larangan jumlah pendaki ganjil, tanpa mereka sadari bahwa salah satu di antara mereka sebenarnya bukan lagi manusia.',
                'rating_avg' => 3.7,
                'rating_default' => 0,
                'is_active' => true,
                'poster' => 'posters/sekawan-limo.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('films')->insert($films);
    }
}